Repository Kong/kubernetes-testing-framework, pull requests merged in 2021-07, with the labels that each got.

#42 chore: add codecov to ci
  .github/workflows/test_integration_with_coverage.yaml
  .github/workflows/test_unit.yaml
  Makefile
  README.md
Labels: enhancement

#45 chore: cleanup github actions workflows
  .github/workflows/release.yaml
  .github/workflows/test_integration_with_coverage.yaml
  .github/workflows/tests.yaml
  Makefile
Labels: enhancement

#47 Set up Dependabot for go dependencies and github actions
  .github/dependabot.yml
Labels: enhancement, pending author feedback

#56 Fix typo
  pkg/utils/kong/fake_admin_api_test.go
Labels: docs

#58 [feat] add k8s version for environment builder
  .github/workflows/tests.yaml
  .gitignore
  internal/cmd/environments.go
  pkg/environments/builder.go
Labels: enhancement

#60 fix: update containerd dep to v1.4.8
  go.mod
  go.sum
Labels: security

#64 fix: support clusterIP services for proxy
  pkg/clusters/addons/kong/kong.go
Labels: bug

#69 fix: disable gke addons
  pkg/clusters/types/gke/builder.go
Labels: bug
