Repository Kong/kubernetes-testing-framework, pull requests merged in 2022-07, with the labels that each got.

#309 feat: add Kuma addon
  pkg/clusters/addons/kuma/addon.go
  pkg/clusters/addons/kuma/builder.go
Labels: area/ci

#327 chore(ci): use kong-license action to obtain license from pulp
  .github/workflows/release-testing.yaml
  .github/workflows/tests.yaml
Labels: github_actions

#330 feat: add calico CNI option for kind clusters
  CHANGELOG.md
  go.mod
  go.sum
  internal/cmd/ktf/environments.go
  pkg/clusters/addons/certmanager/addon.go
  pkg/clusters/addons/kuma/addon.go
  pkg/clusters/types/kind/builder.go
  pkg/clusters/types/kind/utils.go
  pkg/clusters/utils.go
  pkg/environments/builder.go
  test/integration/calico_test.go
  test/integration/certmanager_test.go
  test/integration/clusterutils_test.go
Labels: area/feature
