Repository Kong/kubernetes-testing-framework, pull requests merged in 2022-10, with the labels that each got.

#406 chore(ci): use PAT for tagging instead of GITHUB_TOKEN
  .github/workflows/release-testing.yaml
Labels: area/ci

#416 tests: use Github Actions matrix for integration tests
  .github/workflows/tests.yaml
  Makefile
  test/integration/calico_test.go
Labels: area/tests

#415 refactor: move `DumpDiagnostics` from `Cleaner` to `Cluster`
  pkg/clusters/cleanup.go
  pkg/clusters/cluster.go
  pkg/clusters/diagnostics.go
  pkg/clusters/types/gke/cluster.go
  pkg/clusters/types/kind/cluster.go
  test/integration/kongaddon_test.go
Labels: refactor

#417 chore: bump metallb to v0.13.7
  pkg/clusters/addons/metallb/metallb.go
Labels: dependencies

#425 chore: update linter settings
  .github/workflows/lint.yaml
  .golangci.yaml
  Makefile
  internal/utils/cluster_init.go
  pkg/clusters/addons/httpbin/addon.go
  pkg/clusters/types/kind/cluster.go
  pkg/clusters/utils.go
  pkg/utils/kong/fake_admin_api_test.go
Labels: area/ci, area/maintenance

#439 chore(ci): get masked license for each integration test
  .github/workflows/tests.yaml
Labels: area/ci
