Repository Kong/kubernetes-testing-framework, pull requests merged in 2023-09, with the labels that each got.

#801 chore(ci): Bump GKE K8s version from 1.23 to 1.24
  test/e2e/gke_cluster_test.go
Labels: dependencies, area/ci, area/maintenance

#799 chore(deps): bump metallb to v0.13.11
  pkg/clusters/addons/metallb/metallb.go
Labels: dependencies, area/maintenance

#800 chore(go): introduce usage of Go toolchain
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/release-testing.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  go.mod
  go.sum
Labels: dependencies, go, area/ci, area/maintenance

#802 chore: don't use deprecated docker funcs
  pkg/utils/docker/command.go
  pkg/utils/docker/copy.go
  pkg/utils/docker/docker.go
Labels: area/maintenance

#803 chore: remove outdated TODOs
  test/integration/kind_cluster_test.go
  test/integration/kongaddon_test.go
Labels: area/maintenance

#804 chore: prepare v0.39.0
  CHANGELOG.md
Labels: documentation, area/maintenance

#813 chore(deps): remove exclude github.com/docker/docker v24.0.0+incompatible
  go.mod
Labels: dependencies, area/maintenance, area/tests
