Repository Kong/kubernetes-testing-framework, pull requests merged in 2023-02, with the labels that each got.

#519 fix: fix codecov flags
  .github/workflows/tests.yaml
  Makefile
Labels: area/ci, area/tests

#521 fix(ci): checkout repo before go cache
  .github/workflows/tests.yaml
Labels: area/ci

#520 fix: add retry when applying knative manifests
  CHANGELOG.md
  go.mod
  go.sum
  pkg/clusters/addons/knative/knative.go
Labels: area/maintenance

#523 feat: add retry to helm installation and knative manifests apply
  CHANGELOG.md
  internal/retry/command.go
  pkg/clusters/addons/knative/knative.go
  pkg/clusters/addons/kong/addon.go
  pkg/clusters/cleanup.go
  test/integration/kongaddon_test.go
Labels: area/feature

#524 fix(ci): add missing checkout in release testing pipeline
  .github/workflows/release-testing.yaml
Labels: area/ci

#525 fix(ci): fix release names
  .github/workflows/release.yaml
Labels: area/ci

#516 ci: use gh in install.sh for artifacts download
  .github/workflows/tests.yaml
  docs/install.sh
Labels: area/ci

#537 tests(gke): ensure cluster cleanup is always called
  test/e2e/gke_cluster_test.go
Labels: area/tests

#536 fix(kong): upgrade --install and handle error properly
  internal/retry/command.go
  internal/retry/command_test.go
  pkg/clusters/addons/kong/addon.go
  test/integration/kongaddon_test.go
Labels: bug

#541 fix(tests): fix TestKongAddonWithCustomImage which was waiting for LoadBalancer IP without metallb installed
  test/integration/kongaddon_test.go
Labels: bug, area/maintenance

#538 ci: run e2e tests in PR when secret is available
  .github/workflows/tests.yaml
  test/e2e/gke_cluster_test.go
Labels: area/ci

#545 chore: address review from PR 516
  .github/workflows/tests.yaml
  docs/install.sh
Labels: area/maintenance

#548 ci: skip e2es if no GOOGLE_APPLICATION_CREDENTIALS set
  .github/workflows/tests.yaml
Labels: area/ci

#549 ci: fix condition for running e2es
  .github/workflows/tests.yaml
Labels: area/ci

#555 fix: fix calico manifests URL
  CHANGELOG.md
  pkg/clusters/types/kind/utils.go
Labels: bug

#552 feat: make cleaner safe for concurrent use
  CHANGELOG.md
  pkg/clusters/cleanup.go
  pkg/clusters/cleanup_test.go
Labels: area/feature

#553 fix: fix endless loop when cleaning up namespaces
  CHANGELOG.md
  pkg/clusters/cleanup.go
Labels: bug

#554 chore: add more descriptive errors when commands fail
  pkg/clusters/types/kind/builder.go
  pkg/clusters/types/kind/utils.go
  pkg/clusters/utils.go
Labels: area/maintenance

#559 chore: add changelog for v0.29.0
  CHANGELOG.md
Labels: documentation

#566 chore: bump default enterprise gateway image to 3.1.1.3
  CHANGELOG.md
  pkg/clusters/addons/kong/addon.go
  test/integration/enterprise_test.go
Labels: area/maintenance

#569 feat: add retry to kuma helm installation
  pkg/clusters/addons/kuma/addon.go
Labels: area/feature
