Repository Kong/kubernetes-testing-framework, pull requests merged in 2023-06, with the labels that each got.

#703 chore: bump metallb to v0.13.10
  CHANGELOG.md
  pkg/clusters/addons/metallb/metallb.go
Labels: dependencies, area/maintenance

#705 tests: fix TestKongWithNodePort integration test
  test/integration/kongaddon_test.go
Labels: area/tests

#704 ci: fix integration tests aggregate check
  .github/workflows/tests.yaml
Labels: area/ci, area/tests

#706 ci: use separate CI jobs for e2e tests
  .github/workflows/tests.yaml
  Makefile
  test/e2e/gke_cluster_test.go
Labels: area/ci, area/tests

#707 tests(integration): run just 1 test for kind cluster `WithClusterVersion()`
  test/integration/kind_version_test.go
Labels: area/tests

#723 chore(build): get rid of obsolete Go build tags
  test/e2e/gke_cluster_test.go
  test/integration/calico_test.go
  test/integration/certmanager_test.go
  test/integration/cleaner_test.go
  test/integration/clusterutils_test.go
  test/integration/enterprise_test.go
  test/integration/istio_test.go
  test/integration/kind_cluster_test.go
  test/integration/kind_diagnostics_test.go
  test/integration/kind_version_test.go
  test/integration/knative_test.go
  test/integration/kongaddon_test.go
  test/integration/kuma_test.go
  test/integration/metallb_test.go
  test/integration/postgres_test.go
  test/integration/registry_test.go
  test/integration/suite_test.go
  test/integration/utils_k8s_networking_test.go
Labels: area/maintenance
