Repository Kong/kubernetes-testing-framework, pull requests merged in 2023-01, with the labels that each got.

#484 fix(tests): add GITHUB_TOKEN to tests so that they can authenticate against Github API
  .github/workflows/tests.yaml
Labels: area/ci

#490 feat(gke): allow creating subnets
  CHANGELOG.md
  pkg/clusters/types/gke/builder.go
  pkg/clusters/types/gke/builder_test.go
  test/e2e/gke_cluster_test.go
Labels: area/feature

#492 fix(metallb): extend timeout when fetching manifests
  CHANGELOG.md
  pkg/clusters/addons/metallb/metallb.go
Labels: technical debt

#491 feat(gke): allow synchronous cluster teardown
  CHANGELOG.md
  pkg/clusters/types/gke/builder.go
  pkg/clusters/types/gke/cluster.go
  test/e2e/gke_cluster_test.go
Labels: area/feature

#493 docs: update CHANGELOG.md for release v0.25.0
  CHANGELOG.md
Labels: docs

#494 fix(ci): add GH token to release workflow to overcome API rate limits
  .github/workflows/release-testing.yaml
Labels: area/ci

#495 fix: truncate only when allowed length exceeded
  pkg/clusters/types/gke/builder.go
  pkg/clusters/types/gke/builder_test.go
Labels: bug

#498 refactor(gke): use grpc when createSubnet set
  CHANGELOG.md
  pkg/clusters/types/gke/builder.go
Labels: refactor

#499 feat(gke): allow passing labels
  CHANGELOG.md
  go.mod
  go.sum
  pkg/clusters/types/gke/builder.go
Labels: area/feature

#500 docs: update CHANGELOG.md for release v0.26.0
  CHANGELOG.md
Labels: docs

#510 fix: fix Cleaner's cleanup for Gateway API resources
  go.mod
  go.sum
  pkg/clusters/cleanup.go
  pkg/clusters/cleanup_test.go
  test/integration/cleaner_test.go
Labels: bug, area/maintenance
