Repository Kong/kubernetes-testing-framework, pull requests merged in 2023-05, with the labels that each got.

#646 chore: document knative.Builder.WithVersion
  pkg/clusters/addons/knative/builder.go
Labels: area/maintenance

#651 chore(ci): introduce importas and forbidigo to golangci-lint
  .golangci.yaml
  pkg/clusters/cleanup_test.go
Labels: area/ci

#652 chore(tests): add integration test for function WaitForConnectionOnServicePort
  pkg/utils/kubernetes/networking/services.go
  test/integration/utils_k8s_networking_test.go
Labels: area/tests

#671 chore: fix tests on CI by downgrading docker dependency
  go.mod
  go.sum
Labels: dependencies, area/tests

#669 chore: resolve cert-manager dependency after migration from jetstack/cert-manager to cert-manager/cert-manager
  CHANGELOG.md
  go.mod
  go.sum
  pkg/clusters/addons/certmanager/addon.go
  pkg/clusters/addons/registry/addon.go
  pkg/utils/certmanager/create.go
Labels: dependencies

#676 feat: allow setting stdin, stdout and stderr in retry command
  CHANGELOG.md
  internal/retry/command.go
  internal/retry/command_test.go
  pkg/clusters/addons/metallb/metallb.go
Labels: area/feature

#683 feat(kind): allow passing config for Kind clusters with io.Reader
  CHANGELOG.md
  pkg/clusters/types/kind/builder.go
  pkg/clusters/types/kind/utils.go
  test/integration/kind_cluster_test.go
Labels: area/feature
